repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path=.isort.cfg"]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.0'
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
        language_version: python3
        args: ["--config-file=mypy.ini"]
